/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.escom.resdes.ui.client;

import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.escom.resdes.app.service.CestaService;
import org.escom.resdes.app.service.CestaServiceImp;
import org.escom.resdes.app.service.StoreService;
import org.escom.resdes.app.service.StoreServiceImp;
import org.escom.resdes.model.Catalogo;
import org.escom.resdes.model.Cesta;
import org.escom.resdes.model.Orden;
import org.escom.resdes.model.Producto;
import org.escom.resdes.repository.ProductoRepository;
import org.escom.resdes.repository.ProductoRepositoryImp;

/**
 *
 * @author darcusfenix
 */
public class CestaUI extends javax.swing.JFrame {

    private ProductoRepository pr;
    private StoreService ss;
    private CestaService cs;
    private float total;

    /**
     * Creates new form ServerAdmin
     */
    public CestaUI() {
        initComponents();
        pr = new ProductoRepositoryImp();
        ss = new StoreServiceImp();
        cs = new CestaServiceImp();
        updateTable();
    }

    public void updateTable() {
        total = 0f;
        Cesta cesta = null;
        cesta = ss.getCesta();
        if (cesta != null) {
            List<Orden> ordenes = null;
            ordenes = cesta.getOrdenes();
            if (ordenes.size() == 0) {
                this.dispose();
                btn_finalizar_compra.setVisible(false);
                this.label_total.setText("$ 00.00");
                JOptionPane.showMessageDialog(null, "La cesta está vacía");
            }

            DefaultTableModel model = (DefaultTableModel) table_productos_cesta.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            for (Orden orden : ordenes) {
                total += orden.getProducto().getCosto() * orden.getCantidad();
                Producto producto = orden.getProducto();
                Object[] row = {producto.getSku(), producto.getNombre(), producto.getDescripcion(), producto.getUrlImagen(), producto.getCosto(), orden.getCantidad()};
                model.addRow(row);
            }
            this.label_total.setText("$ " + total);
            cesta.setTotal(total);
            ss.saveCesta(cesta);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_productos_cesta = new javax.swing.JTable();
        btn_delete_producto_cesta = new javax.swing.JButton();
        btn_edit_producto_cesta = new javax.swing.JButton();
        btn_show_producto_cesta = new javax.swing.JButton();
        btn_update_cesta = new javax.swing.JButton();
        btn_finalizar_compra = new javax.swing.JButton();
        label_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cesta");

        table_productos_cesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sku", "nombre", "descripción", "imagen", "costo", "cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_productos_cesta);

        btn_delete_producto_cesta.setText("QUITAR");
        btn_delete_producto_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_producto_cestaActionPerformed(evt);
            }
        });

        btn_edit_producto_cesta.setText("MODIFICAR");
        btn_edit_producto_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_producto_cestaActionPerformed(evt);
            }
        });

        btn_show_producto_cesta.setText("VER PRODUCTO");
        btn_show_producto_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_producto_cestaActionPerformed(evt);
            }
        });

        btn_update_cesta.setText("ACTUALIZAR MI CESTA");
        btn_update_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_cestaActionPerformed(evt);
            }
        });

        btn_finalizar_compra.setText("FINALIZAR COMPRA");
        btn_finalizar_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_compraActionPerformed(evt);
            }
        });

        label_total.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        label_total.setText("TOTAL: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_delete_producto_cesta)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit_producto_cesta)
                        .addGap(18, 18, 18)
                        .addComponent(btn_show_producto_cesta)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_cesta)
                        .addGap(18, 18, 18)
                        .addComponent(btn_finalizar_compra)
                        .addGap(184, 184, 184)
                        .addComponent(label_total)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete_producto_cesta)
                    .addComponent(btn_edit_producto_cesta)
                    .addComponent(btn_show_producto_cesta)
                    .addComponent(btn_update_cesta)
                    .addComponent(btn_finalizar_compra)
                    .addComponent(label_total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_show_producto_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_producto_cestaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Integer index = table_productos_cesta.getSelectedRow();
                if (index >= 0) {
                    DefaultTableModel model = (DefaultTableModel) table_productos_cesta.getModel();
                    Producto producto = null;
                    Integer skuIndex = (Integer) model.getValueAt(index, 0);

                    Catalogo c = new Catalogo();
                    c = ss.getCatalogo();
                    List<Producto> productos = null;
                    productos = c.getProductos();

                    for (Producto item : productos) {
                        if (item.getSku().equals(skuIndex)) {
                            producto = item;
                            break;
                        }
                    }
                    new ProductoUI(producto).setVisible(true);
                }
            }
        });
    }//GEN-LAST:event_btn_show_producto_cestaActionPerformed

    private void btn_update_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_cestaActionPerformed
        updateTable();
    }//GEN-LAST:event_btn_update_cestaActionPerformed

    private void btn_delete_producto_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_producto_cestaActionPerformed
        Integer index = table_productos_cesta.getSelectedRow();
        if (index >= 0) {
            DefaultTableModel model = (DefaultTableModel) table_productos_cesta.getModel();
            Producto producto = null;
            Integer skuIndex = (Integer) model.getValueAt(index, 0);

            Catalogo c = new Catalogo();
            c = ss.getCatalogo();
            List<Producto> productos = null;
            productos = c.getProductos();

            for (Producto item : productos) {
                if (item.getSku().equals(skuIndex)) {
                    producto = item;
                    break;
                }
            }
            cs.removeProductoOfCesta(producto);
            JOptionPane.showMessageDialog(null, "Se quitó el producto de la cesta");
        }
    }//GEN-LAST:event_btn_delete_producto_cestaActionPerformed

    private void btn_edit_producto_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_producto_cestaActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Integer index = table_productos_cesta.getSelectedRow();
                if (index >= 0) {
                    DefaultTableModel model = (DefaultTableModel) table_productos_cesta.getModel();
                    Orden orden = null;
                    Integer skuIndex = (Integer) model.getValueAt(index, 0);

                    Cesta c = null;
                    c = ss.getCesta();
                    List<Orden> ordenes = null;
                    ordenes = c.getOrdenes();

                    for (Orden item : ordenes) {
                        if (item.getProducto().getSku().equals(skuIndex)) {
                            orden = item;
                            break;
                        }
                    }
                    new ProductoUI(orden).setVisible(true);
                }
            }
        });
    }//GEN-LAST:event_btn_edit_producto_cestaActionPerformed

    private void btn_finalizar_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_compraActionPerformed
        File f = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("SELECCIONA DÓNDE GUARDAR TU TIKECT");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = chooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            Cesta cesta = ss.getCesta();
            f = chooser.getSelectedFile();
            System.err.println(f);
            ss.finalizarCompra(cesta);
            ss.generarTikect(cesta, f);
            this.dispose();
        }
    }//GEN-LAST:event_btn_finalizar_compraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CestaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CestaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CestaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CestaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CestaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_producto_cesta;
    private javax.swing.JButton btn_edit_producto_cesta;
    private javax.swing.JButton btn_finalizar_compra;
    private javax.swing.JButton btn_show_producto_cesta;
    private javax.swing.JButton btn_update_cesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_total;
    private javax.swing.JTable table_productos_cesta;
    // End of variables declaration//GEN-END:variables
}
