/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.escom.resdes.ui.client;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.escom.resdes.app.config.Propiedades;
import org.escom.resdes.app.service.CestaService;
import org.escom.resdes.app.service.CestaServiceImp;
import org.escom.resdes.app.service.StoreService;
import org.escom.resdes.app.service.StoreServiceImp;
import org.escom.resdes.model.Orden;
import org.escom.resdes.model.Producto;

/**
 *
 * @author darcusfenix
 */
public class ProductoUI extends javax.swing.JFrame {

    private Producto producto;
    private Orden orden;
    private StoreService ss;
    private CestaService cs;

    /**
     * Creates new form ProductoUI
     */
    public ProductoUI() {
        initComponents();
    }

    public ProductoUI(Producto producto) {
        initComponents();
        this.producto = producto;
        this.ss = new StoreServiceImp();
        this.cs = new CestaServiceImp();
        updateInputs(this.producto);
    }

    public ProductoUI(Orden orden) {
        initComponents();
        this.orden = orden;
        this.producto = this.orden.getProducto();
        this.ss = new StoreServiceImp();
        this.cs = new CestaServiceImp();
        updateInputs(this.orden);
    }

    public void updateInputs(Producto producto) {
        ImageIcon image = new ImageIcon(Propiedades.PATH_CLIENTE + "PATH_CLIENT/IMAGES/" + this.producto.getUrlImagen());
        this.label_img.setIcon(image);
        this.tf_descripcion_product.setText(this.producto.getDescripcion());
        this.tf_name_product.setText(this.producto.getNombre());
        this.label_costo_product.setText("USD $ " + Float.toString(this.producto.getCosto()));
        this.tf_cantidad_product.setText(this.producto.getCantidad().toString());
        this.tf_cantidad_product.setEditable(false);
        this.tf_descripcion_product.setEditable(false);
        this.tf_name_product.setEditable(false);
        this.label_cantidad.setText("EN EXISTENCIA");
        this.btn_update_cantidad.setVisible(false);
    }

    public void updateInputs(Orden orden) {
        ImageIcon image = new ImageIcon(Propiedades.PATH_CLIENTE + "PATH_CLIENT/IMAGES/" + this.orden.getProducto().getUrlImagen());
        this.label_img.setIcon(image);
        this.tf_descripcion_product.setText(this.orden.getProducto().getDescripcion());
        this.tf_name_product.setText(this.orden.getProducto().getNombre());
        this.label_costo_product.setText("USD $ " + Float.toString(this.orden.getProducto().getCosto()));
        this.tf_cantidad_product.setText(this.orden.getCantidad().toString());
        this.tf_cantidad_product.setEditable(true);
        this.tf_descripcion_product.setEditable(false);
        this.tf_name_product.setEditable(false);
        this.label_cantidad.setText("CANTIDAD REQUERIDA");
        this.btn_add_cesta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_img = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_cantidad = new javax.swing.JLabel();
        label_costo_product = new javax.swing.JLabel();
        tf_name_product = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_descripcion_product = new javax.swing.JTextArea();
        tf_cantidad_product = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_add_cesta = new javax.swing.JButton();
        btn_update_cantidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto");

        label_img.setText("IMAGEN");

        label_name.setText("NOMBRE:");

        jLabel1.setText("DESCRIPCION:");

        label_cantidad.setText("CANTIDAD:");

        label_costo_product.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        label_costo_product.setText("COSTO");

        tf_descripcion_product.setColumns(20);
        tf_descripcion_product.setRows(5);
        jScrollPane1.setViewportView(tf_descripcion_product);

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_add_cesta.setText("AGREGAR A LA CESTA");
        btn_add_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_cestaActionPerformed(evt);
            }
        });

        btn_update_cantidad.setText("AZTUALIZAR ");
        btn_update_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_cantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_update_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_add_cesta)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_name_product)
                    .addComponent(tf_cantidad_product)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cantidad)
                            .addComponent(label_name)
                            .addComponent(jLabel1)
                            .addComponent(label_costo_product))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_img, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_name)
                        .addGap(2, 2, 2)
                        .addComponent(tf_name_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_cantidad_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(label_costo_product)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add_cesta)
                            .addComponent(jButton1)
                            .addComponent(btn_update_cantidad))
                        .addGap(90, 90, 90))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_add_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_cestaActionPerformed
        cs.addProductoToCesta(this.producto, 1);
        JOptionPane.showMessageDialog(null, "Se agregó el producto a la cesta");
        this.dispose();
    }//GEN-LAST:event_btn_add_cestaActionPerformed

    private void btn_update_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_cantidadActionPerformed
        try {
            Integer nuevaCantidad = Integer.parseInt(this.tf_cantidad_product.getText());
            if (nuevaCantidad > 0) {
                cs.addProductoToCesta(this.producto, nuevaCantidad);
                JOptionPane.showMessageDialog(null, "Se actualizó el producto en la cesta");
                this.dispose();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_update_cantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_cesta;
    private javax.swing.JButton btn_update_cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cantidad;
    private javax.swing.JLabel label_costo_product;
    private javax.swing.JLabel label_img;
    private javax.swing.JLabel label_name;
    private javax.swing.JTextField tf_cantidad_product;
    private javax.swing.JTextArea tf_descripcion_product;
    private javax.swing.JTextField tf_name_product;
    // End of variables declaration//GEN-END:variables
}
